test: default
	./test_allocator 10000
	./test_allocator 30000
	./test_array 10 0
	./test_array 10 1 || echo "Abort is normal"
	./test_array 10 2 || echo "Abort is normal"
	./test_array 10 3 || echo "Abort is normal"
	./test_bitptr
	./test_bitstring
	./test_cppbitstring 10
	./test_cppbitstring 1000
	./test_crash_allocator 0 || echo "Abort is normal"
	./test_crash_allocator 1 || echo "Abort is normal"
	./test_crash_allocator 2 || echo "Abort is normal"
	./test_crash_allocator 3 || echo "Abort is normal"
	./test_crash_allocator 4
	./test_int_utils 10
	./test_int_utils 10000
	./test_item_allocator 1
	./test_item_allocator 10
	./test_item_allocator 100000
	./test_object
	./test_timer 100
