#cmakedefine HAVE_INTTYPES_H @HAVE_INTTYPES_H@
#cmakedefine HAVE_STDINT_H @HAVE_STDINT_H@
#cmakedefine HAVE_SSTREAM @HAVE_SSTREAM@

#cmakedefine PACKAGE_STRING "@PACKAGE_STRING@"
#cmakedefine PACKAGE_VERSION "@PACKAGE_VERSION@"
#cmakedefine VERSION "@VERSION@"
#cmakedefine DBM_VERSION "@DBM_VERSION@"
#cmakedefine PACKAGE_REVISION "@PACKAGE_REVISION@"

#cmakedefine PACKAGE_YEAR "@PACKAGE_YEAR@"
#cmakedefine PACKAGE_MONTH "@PACKAGE_MONTH@"

#cmakedefine PACKAGE_NAME "@PACKAGE_NAME@"
#cmakedefine PACKAGE_TARNAME "@PACKAGE_TARNAME@"
#cmakedefine PACKAGE_URL "@PACKAGE_URL@"
#cmakedefine PACKAGE_BUGREPORT "@PACKAGE_BUGREPORT@"
#cmakedefine COMPILER_STRING "@COMPILER_STRING@"


