#cmakedefine UDBM_PACKAGE_STRING "@UDBM_PACKAGE_STRING@"
#cmakedefine UDBM_VERSION "@UDBM_VERSION@"

#cmakedefine ENABLE_STORE_MINGRAPH @ENABLE_STORE_MINGRAPH@
#cmakedefine ENABLE_DBM_NEW @ENABLE_DBM_NEW@
